# Generated by Django 5.1 on 2024-08-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Test_Category",
            },
        ),
        migrations.CreateModel(
            name="UploadTestInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("test_fees", models.FloatField()),
                ("test_id", models.CharField(max_length=255)),
                ("patient_id", models.CharField(max_length=255)),
                (
                    "test_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="backend.testcategory",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="upload_test_information",
        ),
    ]
