# Generated by Django 5.1 on 2024-08-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_testcategory_uploadtestinformation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test_request_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateTimeField()),
                (
                    "test_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category1",
                        to="backend.testcategory",
                    ),
                ),
            ],
        ),
    ]
