# Generated by Django 5.1 on 2024-08-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_upload_result_test_request_details_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test_request_details",
            options={"verbose_name_plural": "Test Request detail"},
        ),
        migrations.AlterModelOptions(
            name="upload_result",
            options={"verbose_name_plural": "upload_result"},
        ),
        migrations.AlterModelOptions(
            name="uploadtestinformation",
            options={"verbose_name_plural": "Uploaded_test_info"},
        ),
    ]
