# Generated by Django 5.1 on 2024-08-27 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_test_request_details_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test_request_details",
            name="time_requested",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="test_request_details",
            name="phone_number",
            field=models.IntegerField(default=9999999999),
        ),
    ]
