# Generated by Django 5.1 on 2024-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_test_request_details_time_requested_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="onlinepayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upi", models.IntegerField()),
                ("amount", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "onlinepayment",
            },
        ),
    ]
