# Generated by Django 5.1 on 2024-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_onlinepayments"),
    ]

    operations = [
        migrations.CreateModel(
            name="blood_donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "blodd_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="A+",
                        max_length=255,
                    ),
                ),
                ("donation_date", models.DateField()),
            ],
        ),
    ]
