# Generated by Django 5.1 on 2024-09-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_blood_donation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blood_donation",
            options={"verbose_name_plural": "Blood Donations"},
        ),
        migrations.RenameField(
            model_name="blood_donation",
            old_name="blodd_group",
            new_name="blood_group",
        ),
    ]
