# Generated by Django 5.1 on 2024-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_blood_donation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                ("mobile_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=500)),
                ("units", models.PositiveIntegerField()),
                ("expiry_date", models.DateField()),
            ],
        ),
    ]
