# Generated by Django 5.1 on 2024-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_donor"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="A+",
                max_length=255,
            ),
        ),
    ]
