# Generated by Django 5.1 on 2024-09-19 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_donor_blood_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadtestinformation",
            name="image",
            field=models.ImageField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
    ]
