# Generated by Django 5.1 on 2024-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_uploadtestinformation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadtestinformation",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
