# Generated by Django 5.1 on 2024-09-20 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_alter_uploadtestinformation_test_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadtestinformation",
            options={},
        ),
        migrations.RemoveField(
            model_name="uploadtestinformation",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="uploadtestinformation",
            name="test_description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadtestinformation",
            name="test_duration",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadtestinformation",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="uploadtestinformation",
            name="test_category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="uploadtestinformation",
            name="test_fees",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="uploadtestinformation",
            name="test_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="uploadtestinformation",
            name="test_name",
            field=models.CharField(max_length=100),
        ),
    ]
